export const API_HOST = "http://localhost:5000";


// characters
export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTER = "GET_CHARACTER";

export const FILTER_STATUS = "FILTER_STATUS";
export const NO_FILTER_STATUS = "NO_FILTER_STATUS";

export const FILTER_GENDER = "FILTER_GENDER";
export const NO_FILTER_GENDER = "NO_FILTER_GENDER";

export const FILTER_SEARCH = 'FILTER_SEARCH';
export const NO_FILTER_SEARCH = 'NO_FILTER_SEARCH';

export const RESET_ALL = 'RESET_ALL';


// locations
export const GET_LOCATIONS = 'GET_LOCATIONS';

export const FILTER_NAME_LOCATION = 'FILTER_NAME_LOCATION';
export const NO_FILTER_NAME_LOCATION = 'NO_FILTER_NAME_LOCATION';

export const FILTER_TYPE_LOCATION = 'FILTER_TYPE_LOCATION';
export const NO_FILTER_TYPE_LOCATION = 'NO_FILTER_TYPE_LOCATION';

export const RESET_LOCATION = 'RESET_LOCATION';